//Exercicio 04 - Efetuar a leitura de 3 valores inteiros e apresentar 
//como resultado final o quadrado da soma dos números.
//Autor: Alessandro Ap. Antonio
//Data: 07/08/2017

INICIO
    inteiro n1, n2, n3, soma, quadradoSoma;
    ESCREVER "Digite um numero: ";
    LER n1;
    ESCREVER "Digite um numero: ";
    LER n2;
    ESCREVER "Digite um numero: ";
    LER n3;
    soma <- n1 + n2 + n3;
    quadradoSoma <- soma * soma;
    ESCREVER "O Quadrado da soma é: ", quadradoSoma;
FIM
    
    
