//Exercicio 08 - Crie um algoritmo que receba 4 notas de um aluno e calcule a sua média.
//Autor: Alessandro Ap. Antonio
//Data: 07/08/2017
inicio
    real n1 , n2 , n3 , n4 , media;
    escrever "Digite a nota 1: ";
    ler n1;
    escrever "Digite a nota 2: ";
    ler n2;
    escrever "Digite a nota 3: ";
    ler n3;
    escrever "Digite a nota 4: ";
    ler n4;
    media <- ( n1 + n2 + n3 + n4 ) / 4;
    escrever "A média é: " , media;
fim

